### ISSUE TITLE
Start tmux-butler in path mode

### ISSUE THREAD

**Issue by edi9999** [woodstok/tmux-butler#3]
Tmux-butler, with fzf, starts by default in a global mode.

I would like tmux-butler to start in path mode, but still allow me to change modes (ie if I do : bind-key -n M-p run-shell -b "$HOME/.tmux-butler/modes/paths"), it won't let me change modes.

I also have tried adding the following to my .butlerrc : 

```
export READER="$HOME/.tmux/plugins/tmux-butler/scripts/capture_panes | $HOME/.tmux/plugins/tmux-butler/scripts/quetty -path"
```

But this does'nt show whole paths containing a slash, such as `./docs/test/foo.pdf` (which does work if I hit `ctrl-p` in the fzf session).

**Comment by woodstok** [comment]
Your butlerrc change does not work because after the READER stage, it still goes through `quetty-fzf`, which triggers a `-word` tokenizer as the starting mode. 

Instead i'll try to add a "starting" mode flag to quetty-fzf to help us make this more customisable

**Comment by woodstok** [comment]
@edi9999 Can you try using the new quetty-filter mode to specify the path and let me know if it works?

**Comment by edi9999** [comment]
It didn't work out of the box, but I got the patch to fix it : 

```
diff --git a/viewers/tmux-split b/viewers/tmux-split
index f2a7b7c..5e89add 100755
--- a/viewers/tmux-split
+++ b/viewers/tmux-split
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
-ENVLIST="-e BUTLERTMPDIR=$BUTLERTMPDIR -e BUTLERDEBUG=$BUTLERDEBUG"
+ENVLIST="-e BUTLERTMPDIR=$BUTLERTMPDIR -e BUTLERDEBUG=$BUTLERDEBUG -e QUETTYFZF_START=$QUETTYFZF_START"
 tmux split-window $ENVLIST -v -l 10  bash $1 &
```

The QUETTYFZF_START variable was not passed to the subprocess.

**Comment by woodstok** [comment]
I see. I'll have to clean up the environment handling a bit later. 
Where did you set the QUETTYFZF_START?

**Comment by edi9999** [comment]
I didn't directly, I just used this binding : 

bind -r M-i run-shell -b "$HOME/.tmux/plugins/tmux-butler/modes/quetty-filter -start path"

**Comment by woodstok** [comment]
Have cleaned up the environment handling a bit. That should fix your issue.

**Comment by edi9999** [comment]
It works well indeed. Thanks !
