### ISSUE TITLE
In quetty-fzf, avoid binding ctrl-w and ctrl-e

### ISSUE THREAD

**Issue by edi9999** [woodstok/tmux-butler#6]
Fzf uses readline bindings, such as ctrl-w to delete the word under the cursor and ctrl-e to go the end of the line. 

I use those bindings a lot, so it is annoying to me if they are overwritten.

I would suggest to use the alt bindings instead : 

keymap['alt-w']='word'
keymap['altl-e']='nospace'
keymap['altl-h']='hash'
keymap['altl-n']='num'
keymap['altl-p']='path'
keymap['altl-i']='ip'
keymap['altl-l']='line'

**Comment by woodstok** [comment]
Good point. I had other very specific tmux bindings that were clashing with these and were always blinded by my own config, but these seem like more sensibile shortcuts. Will try to change this and bring in some customisation options.

**Comment by rafcamlet** [comment]
Also `p` and `n` are common unix "moving keys".

> https://github.com/junegunn/fzf#using-the-finder
> CTRL-J / CTRL-K (or CTRL-N / CTRL-P) to move cursor up and down

**Comment by woodstok** [comment]
Moved all the key-bindings to Alt. They seem more sensible.
